### ISSUE TITLE
TO DO List

### ISSUE THREAD

**Issue by SANDQVISTT** [Sydow75/Sydow75-VH-ovningar-Michaela-Sydow#10]
Detta är en TODO List. 
[ ] ändra header.
[ ] ändra bakgrundfärgen.

**Comment by Othmaann** [comment]
- [] Ändra presentationen så att alla i teamet får sitt namn

**Comment by Othmaann** [comment]
- []

**Comment by SANDQVISTT** [comment]
- pamsda

**Comment by SANDQVISTT** [comment]
- [ ] bla bla bla
- [ ] bla bla bla
- [ ] bla bla bla
